# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os: linux
dist: xenial
sudo: true
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
    - julia: nightly
before_install:
  - sudo apt-get install libblas3 libc6 libgcc1 libgfortran3 libgmp10 libgsl2 liblapack3 libstdc++6 zlib1g
  - export VERSION=6.0.1
  - wget http://scip.zib.de/download/release/SCIPOptSuite-$VERSION-Linux.deb
  - sudo dpkg -i SCIPOptSuite-$VERSION-Linux.deb
  - export SCIPOPTDIR=/usr
script:
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("PipeLayout"); Pkg.test("PipeLayout"; coverage=true)'
after_success:
  - julia -e 'VERSION < v"1.1" && exit(0); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
