# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
dist: trusty
sudo: required
services:
  - docker
before_install:
  - echo "**** pulling Docker image"
  - docker pull leethargo/scip-julia
notifications:
  email: false
script:
  - echo "**** running Docker"
  - docker run --env-file travis_docker_env.list -t -a STDOUT -a STDIN -a STDERR -v $PWD:/mnt leethargo/scip-julia /mnt/travis_docker_test_script.sh $TRAVIS_JULIA_VERSION
