# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
sudo: false # use a docker worker
addons:
  apt_packages:
  - libgmp-dev
script:
# first compile SCIP and add SCIP.jl
  - wget http://scip.zib.de/download/release/scipoptsuite-5.0.0.tgz
  - tar xzf scipoptsuite-5.0.0.tgz
  - cd scipoptsuite-5.0.0/
  - export SCIPOPTDIR=`pwd`/install
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$SCIPOPTDIR ..
  - make
  - make install
  - cd ../..
  - julia -e 'Pkg.add("SCIP")'
# now fetch PipeLayout.jl and test it
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("PipeLayout"); Pkg.test("PipeLayout"; coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("PipeLayout")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
