# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os: linux
dist: xenial
sudo: true
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
    - julia: nightly
before_install:
  - sudo apt-get install libblas-dev liblapack-dev gfortran
  - export VERSION=6.0.1
  - wget http://scip.zib.de/download/release/SCIPOptSuite-$VERSION-Linux.deb
  - sudo dpkg -i SCIPOptSuite-$VERSION-Linux.deb
script:
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("PipeLayout"); Pkg.test("PipeLayout"; coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
